name: Run tests

on:
  push:
    branches:
      - master
      - staging

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Create mongoDB Docker container
        run: sudo docker run -d -p 27017:27017 mongo:latest
      - run: npm install
      - run: npm run build --if-present
      - run: npm test

  test:
    uses: ./.github/workflows/run-tests.yml

  coverage:
    needs: test
    steps:
      - run: npm coverage
